services:
  payload:
    container_name: payload-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
      - '24678:24678'  
    volumes:
      - .:/app  
      - /app/node_modules  
    command: pnpm run dev  
    env_file:
      - .env
    networks:
      - app-network