name: Deploy on Push to Main

on:
  push:
    branches:
      - main

env:
  APP_PATH: /root/apps/bettermoveco

jobs:
  deploy:
    name: Deploy App to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy Code to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "${{ env.APP_PATH }}"
          rm: true

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ env.APP_PATH }}
            chmod +x start-application.sh
            ./start-application.sh
